# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='categories')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('alt', models.CharField(blank=True, max_length=128, verbose_name='short description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tienda.Category')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=' ', upload_to='products'),
            preserve_default=False,
        ),
    ]
