# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_product_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'imagen de producto', 'verbose_name_plural': 'imagenes de producto'},
        ),
    ]
