# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_catalogdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdiscount',
            name='days',
            field=models.CommaSeparatedIntegerField(default='', max_length=20, verbose_name='D\xedas'),
        ),
    ]
