# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20160422_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdiscount',
            name='days',
            field=models.CommaSeparatedIntegerField(blank=True, default='1,2,3,4,5,6,7', max_length=20, verbose_name='D\xedas'),
        ),
    ]
