# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20160422_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogDiscountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.IntegerField(choices=[(1, 'Categoria'), (2, 'Producto')], verbose_name='Tipo')),
                ('category', models.ManyToManyField(blank=True, null=True, to='tienda.Category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tienda.CatalogDiscount')),
                ('product', models.ManyToManyField(blank=True, null=True, to='tienda.Product')),
            ],
            options={
                'verbose_name': 'Regla de cat\xe1logo',
                'verbose_name_plural': 'Reglas de cat\xe1logo',
            },
        ),
    ]
