# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('tienda', '0009_auto_20160425_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='T\xedtulo')),
                ('first_name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=256, verbose_name='Apellido')),
                ('street_address_1', models.CharField(max_length=256, verbose_name='Direcci\xf3n')),
                ('street_address_2', models.CharField(blank=True, default='', max_length=256, verbose_name='Direcci\xf3n 2')),
                ('city', models.CharField(max_length=256, verbose_name='Ciudad')),
                ('city_area', models.CharField(max_length=128, verbose_name='Barrio')),
                ('phone', models.CharField(max_length=30, verbose_name='Tel\xe9fono')),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('addresses', models.ManyToManyField(blank=True, to='tienda.Address')),
                ('default_shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tienda.Address', verbose_name='Default shipping address')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
        ),
    ]
