# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_auto_20160523_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descuentos aplicados'),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(editable=False, max_length=36, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('payment-pending', 'Pendiente de pago'), ('fully-paid', 'Pagada'), ('cancelled', 'Cancelado')], default='payment-pending', max_length=30, verbose_name='Estado'),
        ),
    ]
