# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_auto_20160524_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_from',
        ),
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.CharField(default='-', max_length=100, verbose_name='Informaci\xf3n adicional de \xf3rden'),
        ),
    ]
