# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_auto_20160524_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Direcci\xf3n', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categor\xeda', 'verbose_name_plural': 'categor\xedas'},
        ),
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'verbose_name': 'Imagen de categor\xeda', 'verbose_name_plural': 'Im\xe1genes de categor\xeda'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\xd3rden', 'verbose_name_plural': '\xd3rdenes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Im\xe1genes de producto'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Producto de \xf3rden', 'verbose_name_plural': 'Productos de \xf3rden'},
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(b'test', b'TEST')], max_length=30, verbose_name='M\xe9todo de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(max_length=32, unique=True, verbose_name='Referencia'),
        ),
    ]
