# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_auto_20160602_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
    ]
