# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_auto_20160603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(b'contraentrega_efectivo', b'Contra entrega efectivo'), (b'contraentrega_tarjeta', b'Contra entrega tarjeta'), (b'voucher', b'Pago Bono/Voucher')], max_length=30, verbose_name='M\xe9todo de pago'),
        ),
    ]
