# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_auto_20160623_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='born_date',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='genre',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=50, verbose_name='G\xe9nero'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(b'test', b'TEST')], max_length=30, verbose_name='M\xe9todo de pago'),
        ),
    ]
