# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_auto_20160630_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_address_1_p1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_1_p2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_1_p3',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_1_p4',
        ),
    ]
