# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_auto_20160630_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='confirm_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='token',
            field=models.CharField(default='', max_length=36),
        ),
    ]
