# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0034_auto_20160718_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Descripci\xf3n'),
        ),
    ]
