# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0035_auto_20160804_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(b'test', b'TEST')], max_length=30, verbose_name='M\xe9todo de pago'),
        ),
    ]
