# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0036_auto_20160927_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-pk'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
