# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 02:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0038_auto_20161004_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Descripci\xf3n'),
        ),
    ]
